<a href="https://colab.research.google.com/github/RonaldN21/Repositorio1/blob/master/Pr%C3%A1ctica5/11/2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Clase 5/11/2024 prácticas con PYTHON

Uso de librería numpy

In [2]:
#
import numpy as np
matrixA =np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(matrixA)
print(matrixA.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
(3, 4)


In [3]:
matrixA

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [7]:
print(matrixA[1:3,1:3])

[[22 23]
 [32 33]]


In [10]:
import numpy as np

# Create a 4x3 matrix of integers
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

#To see the output, run the code.
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
import numpy as np

# Create a 4x3 matrix with random integers between 0 and 9
matrixC = np.random.randint(0, 10, size=(4, 3))

#To see the output, run the code.
print(matrixC)
print(matrixC.shape)


[[3 3 2]
 [2 5 1]
 [7 1 7]
 [5 0 7]]
(4, 3)


In [28]:
print(matrix)
col_indices =np.array([0,1,2])
row_indices =np.array([1,2])

for row,col in zip(row_indices,col_indices):
    print(matrix[row,col])

print(row_indices)
print(col_indices)

[[2 7 4]
 [4 0 8]
 [2 5 7]
 [1 0 6]]
4
5
[1 2]
[0 1 2]


In [29]:
mask=matrix>7
print(mask)

[[False False False]
 [False False  True]
 [False False False]
 [False False False]]


In [30]:
print(matrix[mask])

[8]


In [31]:
print(matrix[matrix>7])

[8]


In [32]:
print(matrix)

[[2 7 4]
 [4 0 8]
 [2 5 7]
 [1 0 6]]


In [67]:
arr=matrix
arr[arr % 2 == 0] += 100
print(arr)
matrix

[[102   7 104]
 [104 100 108]
 [102   5   7]
 [  1 100 106]]


array([[102,   7, 104],
       [104, 100, 108],
       [102,   5,   7],
       [  1, 100, 106]])

In [75]:
matrix[2:3, 1:] += 100
matrixFilter = matrix[2:3, 1:]
print(matrixFilter)

[[105 107]]


In [77]:
# prompt: Suma 100 a los valores que sean mayor a 3 y menor a 9 del array matrix

matrix[(matrix > 3) & (matrix < 9)] += 100
print(matrix)



[[102 107 104]
 [104 100 108]
 [102 105 107]
 [  1 100 106]]


In [78]:
filterone =matrix[(matrix > 3) & (matrix < 9)]
matrix[filterone] += 100
print(filterone)

[]


In [85]:
matrixA1 =np.random.randint(0, 10, size=(2, 2))
matrixA2 =np.random.randint(0, 10, size=(2, 2))
print("matrixA1")
print(matrixA1)
print("matrixA2")
print(matrixA2)

matrixA1
[[3 1]
 [6 1]]
matrixA2
[[9 0]
 [9 8]]


In [87]:
print(matrixA1+matrixA2)
print(matrixA1-matrixA2)
print(matrixA1*matrixA2)
print(matrixA1/matrixA2)

[[12  1]
 [15  9]]
[[-6  1]
 [-3 -7]]
[[27  0]
 [54  8]]
[[0.33333333        inf]
 [0.66666667 0.125     ]]
[[1.73205081 1.        ]
 [2.44948974 1.        ]]
[[36  8]
 [63  8]]


<ipython-input-87-8e8dbe35ccad>:4: RuntimeWarning: divide by zero encountered in divide
  print(matrixA1/matrixA2)


In [90]:
print(matrixA1)
print(np.sqrt(matrixA1))

[[3 1]
 [6 1]]
[[1.73205081 1.        ]
 [2.44948974 1.        ]]


In [91]:
matrixC1 =np.random.randint(0, 10, size=(2, 5))
print(matrixC1)
print(matrixC1.shape)

[[2 3 9 6 9]
 [7 7 9 7 3]]
(2, 5)


In [93]:
print(np.mean(matrixC1))

6.2


In [96]:
print(matrixC1.mean(axis=0))

[4.5 5.  9.  6.5 6. ]


In [97]:
print(np.median(matrixC1))

7.0


In [98]:
print(np.std(matrixC1))

2.5219040425836985


In [99]:
print(np.var(matrixC1))

6.36


In [100]:
print(np.min(matrixC1))
print(np.max(matrixC1))

2
9


In [102]:
print(matrixC1)
print(np.argmin(matrixC1))
print(np.argmax(matrixC1))

[[2 3 9 6 9]
 [7 7 9 7 3]]
0
2


In [103]:
print(np.sort(matrixC1))

[[2 3 6 9 9]
 [3 7 7 7 9]]


In [104]:
print(np.sort(matrixC1,axis=0))

[[2 3 9 6 3]
 [7 7 9 7 9]]


In [144]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [140]:
add_rows = np.array([1, 2, 3])
print(add_rows.shape)

(3,)


In [141]:
y=start+add_rows
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [145]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [137]:
col_rowa = np.array([[1,2,3,4]])
col_rowa = col_rowa.T
print(col_rowa)

[[1]
 [2]
 [3]
 [4]]


In [132]:
fil_rows = np.array([[1,2,3]])
print(fil_rows)

[[1 2 3]]


In [143]:
start += col_rowa
print(start)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [146]:
start += fil_rows
print(start)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [149]:
tmp1 =np.array([[1,1],[2,2]])
print(tmp1)



[[1 1]
 [2 2]]


In [150]:
print(np.dot(tmp1,tmp1))

[[3 3]
 [6 6]]


In [152]:
# prompt: Crea dos matrices que sean enteros, que el valor minimo sea 2 y el maximo 50

import numpy as np

# Create a matrix with random integers between 2 and 50 (inclusive)
matrix1 = np.random.randint(2, 51, size=(2, 2))  # Adjust size as needed

# Create another matrix with random integers between 2 and 50 (inclusive)
matrix2 = np.random.randint(2, 51, size=(2, 2))  # Adjust size as needed

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
matrix2

Matrix 1:
[[41 34]
 [47 23]]

Matrix 2:


array([[30, 22],
       [45, 14]])

In [153]:
np.vstack((matrix1,matrix2))

array([[41, 34],
       [47, 23],
       [30, 22],
       [45, 14]])

In [154]:
np.hstack((matrix1,matrix2))

array([[41, 34, 30, 22],
       [47, 23, 45, 14]])